### ISSUE TITLE
Does not seem to ever time out?

### ISSUE THREAD

**Issue by klaw81** [jeboo/Garage_Parking_Assistant#1]
I have used the code almost verbatim and the primary function works wonderfully - bravo to all involved. However, the lights never seem to switch off, even when I leave for 20 minutes with the sensor pointed directly at the roof and nobody in the room.

I have kept the default values for everything except the start and stop distance.

I don't know enough to analyse the code and figure it exactly how it works, but it seems to me like the sleepmode code (lines 49 to 59) belong below the void setup code?

However, I can only assume that this code works for you so perhaps there's another explanation?

**Comment by jeboo** [comment]
The position of the sleepmode function shouldn't affect the logic.

I would try bench testing sleep mode while connected to the Arduino IDE. You can uncomment lines 106-108 and then open the serial monitor (Ctrl-Shift-M) and watch the debug messages. It doesn't sound like you modified DISTANCE_TOLERANCE, so it should be going to sleep in 60s as long as the distance readings don't vary by > 3cm.

**Comment by jeboo** [comment]
Any luck?
