### ISSUE TITLE
slow reaction

### ISSUE THREAD

**Issue by Roman2211696** [jeboo/Garage_Parking_Assistant#2]
Hello, the system is working, but everything is very slow. Before it starts to react at all, I drove it to the garage. Is it possible to speed up the scanning and reaction process? Thx

**Comment by jeboo** [comment]
Hmm, interesting problem. Is it slow to respond before going to sleep the first time? By default it checks once/second when in sleep mode. 

One thing you could try is uncommenting these lines, compile/upload, and open the serial monitor in Arduino (CTRL-SHIFT-M):
`Serial.print("stopdistance: "); Serial.println(stopdistance);`
`Serial.print("distance: ");Serial.println(distance);`
`Serial.print("previous_distance: "); Serial.println(previous_distance);`

You should see rapid scrolling with realtime distance measurements.

You could also lower the polling time when in sleep mode by lowering this #:

#define SLEEP_POLLDELAY     1000    // in milliseconds, delay for each main loop iteration while in sleep mode

**Comment by Roman2211696** [comment]
I reduced the time from 1000 to 100 and on the serial monitor I see that the scan runs after about 4 seconds

`*        Added option (SLEEP_POLLDELAY) to poll less often once in sleep mode
 *        Added option for independent left and right LED strip control; allows differing colors, animations, etc.
 *
 * 0.6 -- Added EEPROM dependency and switched to QuickMedianLib for compatibility with megaAVR boards (tested on Nano Every).
 * 
 * 0.7 -- Cosmetic bugfix: Changed amber LED behavior to only show when car is close to stop.
 */
 
#include <FastLED.h>
#include <MillisTimer.h>
#include <EEPROM.h>
#include <QuickMedianLib.h>

// defining the parameters/layout
#define NUM_LEDS            20      // # LEDs on each side
#define AMBER_LEDS          12       // number of amber LEDs when car is close to stop
#define DISTANCE_TOLERANCE  5       // tolerance to determine if the car is stopped (CENTIMETERS)
#define LED_TIMEOUT         60000   // in milliseconds, time before lights go out (sleep) once car stopped
#define SLEEP_POLLDELAY     100    // in milliseconds, delay for each main loop iteration while in sleep mode

// defining the pins
#define BUTTON_PIN          6       // push-button for setting stopdistance (optional)
#define LED_PIN_L           7       // left-sided LEDs (or both sides if mirror_LEDs set to true)
#define LED_PIN_R           8       // right-sided LEDs (optional), implemented by setting mirror_LEDs below to false
#define TRIG_PIN            9
#define ECHO_PIN            10

// defined variables
int startdistance = 395;            // distance from sensor to begin scan as car pulls in (CENTIMETERS); HC-SR04 max distance is 400CM
int stopdistance = 50;               // parking position from sensor (CENTIMETERS); either specify here, or leave as zero and set dynamically with push-button
const int durationarraysz = 15;     // size of array for distance polling
bool mirror_LEDs = true;            // true = L + R LEDs controlled by pin 7 (mirrored, as in stock project)`

**Comment by Roman2211696** [comment]
I watched the serial monitor and the times when it scans the distance are long and that's why it reacts so slowly

**Comment by jeboo** [comment]
Just tried your settings on my test rig, scans rapidly (about 4-5x/sec). Check your trig + echo pins arent reversed, or maybe try another sensor.

**Comment by Roman2211696** [comment]
I send the videos with a serial monitor. More in the video description
[https://youtube.com/playlist?list=PLk2gvMuS-pnneJ1i5Tt2Y_zM7XXxkV5ki](url)

**Comment by jeboo** [comment]
I was able to reproduce the long-distance lag somewhat yesterday. I updated the scan code to a newer library that should fix the timeout issue. Try this:

#include <FastLED.h>
#include <MillisTimer.h>
#include <EEPROM.h>
#include <NewPing.h>

// defining the parameters/layout
#define NUM_LEDS 20                 // # LEDs on each side
#define AMBER_LEDS 12               // number of amber LEDs when car is close to stop
#define DISTANCE_TOLERANCE 5        // tolerance to determine if the car is stopped (CENTIMETERS)
#define LED_TIMEOUT 60000           // in milliseconds, time before lights go out (sleep) once car stopped
#define SLEEP_POLLDELAY 1000        // in milliseconds, delay for each main loop iteration while in sleep mode

// defining the pins
#define BUTTON_PIN 6 // push-button for setting stopdistance (optional)
#define LED_PIN_L 7 // left-sided LEDs (or both sides if mirror_LEDs set to true)
#define LED_PIN_R 8 // right-sided LEDs (optional), implemented by setting mirror_LEDs below to false
#define TRIG_PIN 9
#define ECHO_PIN 10
#define MAX_DISTANCE        400     // HC-SR04 max distance is 400CM

// defined variables
const int startdistance = 395;      // distance from sensor to begin scan as car pulls in (CENTIMETERS); 
int stopdistance = 50;              // parking position from sensor (CENTIMETERS); either specify here, or leave as zero and set dynamically with push-button
const int durationarraysz = 15;     // number of measurements to take per cycle
bool mirror_LEDs = true;            // true = L + R LEDs controlled by pin 7 (mirrored, as in stock project)

// variables
CRGB leds_L[NUM_LEDS], leds_R[NUM_LEDS];
int distance, previous_distance, increment, i;
unsigned int uS;
uint16_t stopdistance_ee EEMEM;
MillisTimer timer = MillisTimer(LED_TIMEOUT);
bool LED_sleep;

NewPing sonar(TRIG_PIN, ECHO_PIN, MAX_DISTANCE); // NewPing setup of pins and maximum distance.

void sleepmode_start(MillisTimer &mt)
{
  for (i = 0; i < NUM_LEDS; i++)
  {
      leds_L[i] = leds_R[i] = CRGB::Black;
  }
  FastLED.show();

  timer.reset();
  LED_sleep = true;
}

void setup()
{
  LED_sleep = false;
  if (!stopdistance)
  {
    stopdistance = eeprom_read_word(&stopdistance_ee);
  }
  increment = (startdistance - stopdistance)/NUM_LEDS;
  
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
  FastLED.addLeds<WS2812, LED_PIN_L, GRB>(leds_L, NUM_LEDS);
  if (!mirror_LEDs) 
  {
    FastLED.addLeds<WS2812, LED_PIN_R, GRB>(leds_R, NUM_LEDS);
  }
  
  timer.setInterval(LED_TIMEOUT);
  timer.expiredHandler(sleepmode_start);
  timer.setRepeats(0);

  Serial.begin(9600);
}

void loop()
{
  timer.run();

  uS = sonar.ping_median(durationarraysz, MAX_DISTANCE); // Send ping, get ping time in microseconds (uS).
  distance = sonar.convert_cm(uS);
  
  Serial.print("stopdistance: "); Serial.println(stopdistance);
  Serial.print("distance: "); Serial.println(distance);
  Serial.print("previous_distance: "); Serial.println(previous_distance);

  // check if distance changed is within tolerance
  if (abs(distance - previous_distance) < DISTANCE_TOLERANCE)
  {      
    if (!timer.isRunning() && !LED_sleep)
    {
      timer.start();
    }
  }
  else // movement beyond threshold, stop timer and turn off sleep
  {
    previous_distance = distance;
    timer.reset();
    LED_sleep = false;
  }

  // check button state
  if (digitalRead(BUTTON_PIN) == LOW)
  {
    stopdistance = distance;
    eeprom_write_word(&stopdistance_ee, stopdistance);
    increment = (startdistance - stopdistance)/NUM_LEDS;
  }

  if (!LED_sleep)
  {
    if (distance > startdistance)
    {
      for (i = 0; i < NUM_LEDS; i++)
      {
        leds_L[i] = leds_R[i] = CRGB::Black;
      }    
    }
    else if (distance <= stopdistance)
    {
      for (i = 0; i < NUM_LEDS; i++)
      {
        leds_L[i] = leds_R[i] = distance ? CRGB::Red : CRGB::Black;
      }
    }
    else
    {
      for (i = 0; i < NUM_LEDS; i++)
      {
        if (distance > (stopdistance+increment*i))
        {
          leds_L[i] = leds_R[i] = (distance < (stopdistance+(AMBER_LEDS+1)*increment)) ? CRGB::Orange : CRGB::Green;
        }
        else
        {
          leds_L[i] = leds_R[i] = CRGB::Black;
        }
      }
    }    
    FastLED.show();
    delay(50);
  }  
  else
  {
    delay(SLEEP_POLLDELAY);
    Serial.println("Sleep");
  }
}

**Comment by Roman2211696** [comment]
Yes, it works perfectly. Thank you very much for your time and willingness.

**Comment by jeboo** [comment]
Thanks for testing! I'll update the repo soon.
